### PR TITLE
SystemUI: fix black scrim when turning screen on from AOD

### PR DESCRIPTION
**Pull request by McFy49**
* TODO: Maybe add same fade anim as pixel 2

Change-Id: I351a212b2989f56df3b6353f41a379281ed1a9f1
Signed-off-by: Pranav Vashi <neobuddy89@gmail.com>
Signed-off-by: Adesh15 <adesikha15@gmail.com>

### CODE REVIEW

**Comment by ItzLevvie** [comment]
@McFy49 Close?

Please submit patches through LineageOS Gerrit

**Comment by McFy49** [comment]
@ItzLevvie yes, I will submit on gerrit if you can't merge from github

**Comment by ItzLevvie** [comment]
@McFy49 LineageOS doesn't accept any patches through GitHub.

**Comment by McFy49** [comment]
So close it, I will submit properly.

**Comment by ItzLevvie** [comment]
@McFy49 You've the permission to close it. I'm not a LineageOS "maintainer"

**Comment by McFy49** [comment]
Ok

**Pull request closed without merging**
